name: Deploy Portfolio Site

on: 
  push: 
    branches: [ main ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_PORTFOLIO_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths